package com.airline.entity;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Entity
public class Flight{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Column(nullable=false,unique=true) private String flightNumber; private String airlineName; private String source; private String destination;
 private LocalDate departureDate; private LocalTime departureTime; private LocalDate arrivalDate; private LocalTime arrivalTime;
 private BigDecimal price; private int totalSeats; private int availableSeats; @Enumerated(EnumType.STRING) private FlightStatus status=FlightStatus.SCHEDULED;
 @OneToMany(mappedBy="flight",cascade=CascadeType.ALL,orphanRemoval=true) private List<Seat> seats=new ArrayList<>();
 public Long getId(){return id;} public void setId(Long id){this.id=id;} public String getFlightNumber(){return flightNumber;} public void setFlightNumber(String flightNumber){this.flightNumber=flightNumber;} public String getAirlineName(){return airlineName;} public void setAirlineName(String airlineName){this.airlineName=airlineName;} public String getSource(){return source;} public void setSource(String source){this.source=source;} public String getDestination(){return destination;} public void setDestination(String destination){this.destination=destination;} public LocalDate getDepartureDate(){return departureDate;} public void setDepartureDate(LocalDate departureDate){this.departureDate=departureDate;} public LocalTime getDepartureTime(){return departureTime;} public void setDepartureTime(LocalTime departureTime){this.departureTime=departureTime;} public LocalDate getArrivalDate(){return arrivalDate;} public void setArrivalDate(LocalDate arrivalDate){this.arrivalDate=arrivalDate;} public LocalTime getArrivalTime(){return arrivalTime;} public void setArrivalTime(LocalTime arrivalTime){this.arrivalTime=arrivalTime;} public BigDecimal getPrice(){return price;} public void setPrice(BigDecimal price){this.price=price;} public int getTotalSeats(){return totalSeats;} public void setTotalSeats(int totalSeats){this.totalSeats=totalSeats;} public int getAvailableSeats(){return availableSeats;} public void setAvailableSeats(int availableSeats){this.availableSeats=availableSeats;} public FlightStatus getStatus(){return status;} public void setStatus(FlightStatus status){this.status=status;} public List<Seat> getSeats(){return seats;} public void setSeats(List<Seat> seats){this.seats=seats;}
}
